# Generated by Django 3.1.5 on 2021-01-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='link',
        ),
    ]
