# Generated by Django 3.1.5 on 2021-02-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_auto_20210201_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseadactions',
            old_name='ad_id',
            new_name='ad',
        ),
    ]
